name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.5
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.11.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.3.1
  - cpuonly=2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - distro=1.8.0
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.17.0
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.60.1
  - freetype=2.13.3
  - frozendict=2.4.2
  - fsspec=2025.7.0
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.4
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jsonpatch=1.32
  - jsonpointer=2.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.6.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.5.0
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=5.29.3
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.20.0
  - libtiff=4.5.1
  - libtorch=2.6.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - menuinst=2.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.18
  - opentelemetry-api=1.37.0
  - packaging=23.1
  - pandas=2.3.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - pthread-stubs=0.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - scikit-learn=1.7.2
  - scipy=1.16.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.41.2
  - sympy=1.14.0
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.12
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.65.0
  - truststore=0.8.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.41.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - attrs==25.4.0
      - frozenlist==1.8.0
      - multidict==6.7.0
      - propcache==0.4.1
      - psutil==7.1.0
      - torch-geometric==2.7.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/alessio/miniconda3
